# -*- coding: utf-8 -*-

# --------------------------------
# Name:         text_normal.py
# Author:       devshilei@gmail.com
# @Time         2020/7/14 下午4:16
# Description:
# --------------------------------


def normal_dbc_to_sbc(text):
    """
    description: 对文本进行标准化【全角字符替换为半角字符】
                 注：此处保留原始中文句号“。”以及顿号“、”，
                 因其在句子中长用来表平行关系且替换为其他半角字符容易引起歧义。
                 Double Byte Character，简称：DBC
                 Single Byte Character，简称：SBC
    :param text:    待处理文本
    :return:        输出为标准化之后的文本
    """
    text = text.replace("０", "0")
    text = text.replace("１", "1")
    text = text.replace("２", "2")
    text = text.replace("３", "3")
    text = text.replace("４", "4")
    text = text.replace("５", "5")
    text = text.replace("６", "6")
    text = text.replace("７", "7")
    text = text.replace("８", "8")
    text = text.replace("９", "9")
    text = text.replace("Ａ", "A")
    text = text.replace("Ｂ", "B")
    text = text.replace("Ｃ", "C")
    text = text.replace("Ｄ", "D")
    text = text.replace("Ｅ", "E")
    text = text.replace("Ｆ", "F")
    text = text.replace("Ｇ", "G")
    text = text.replace("Ｈ", "H")
    text = text.replace("Ｉ", "I")
    text = text.replace("Ｊ", "J")
    text = text.replace("Ｋ", "K")
    text = text.replace("Ｌ", "L")
    text = text.replace("Ｍ", "M")
    text = text.replace("Ｎ", "N")
    text = text.replace("Ｏ", "O")
    text = text.replace("Ｐ", "P")
    text = text.replace("Ｑ", "Q")
    text = text.replace("Ｒ", "R")
    text = text.replace("Ｓ", "S")
    text = text.replace("Ｔ", "T")
    text = text.replace("Ｕ", "U")
    text = text.replace("Ｖ", "V")
    text = text.replace("Ｗ", "W")
    text = text.replace("Ｘ", "X")
    text = text.replace("Ｙ", "Y")
    text = text.replace("Ｚ", "Z")
    text = text.replace("ａ", "a")
    text = text.replace("ｂ", "b")
    text = text.replace("ｃ", "c")
    text = text.replace("ｄ", "d")
    text = text.replace("ｅ", "e")
    text = text.replace("ｆ", "f")
    text = text.replace("ｇ", "g")
    text = text.replace("ｈ", "h")
    text = text.replace("ｉ", "i")
    text = text.replace("ｊ", "j")
    text = text.replace("ｋ", "k")
    text = text.replace("ｌ", "l")
    text = text.replace("ｍ", "m")
    text = text.replace("ｎ", "n")
    text = text.replace("ｏ", "o")
    text = text.replace("ｐ", "p")
    text = text.replace("ｑ", "q")
    text = text.replace("ｒ", "r")
    text = text.replace("ｓ", "s")
    text = text.replace("ｔ", "t")
    text = text.replace("ｕ", "u")
    text = text.replace("ｖ", "v")
    text = text.replace("ｗ", "w")
    text = text.replace("ｘ", "x")
    text = text.replace("ｙ", "y")
    text = text.replace("ｚ", "z")
    text = text.replace("（", "(")
    text = text.replace("）", ")")
    text = text.replace("〔", "[")
    text = text.replace("〕", "]")
    text = text.replace("【", "[")
    text = text.replace("】", "]")
    text = text.replace("〖", "[")
    text = text.replace("〗", "]")
    text = text.replace("“", "\"")
    text = text.replace("”", "\"")
    text = text.replace("｛", "{")
    text = text.replace("｝", "}")
    text = text.replace("《", "<")
    text = text.replace("》", ">")
    text = text.replace("％", "%")
    text = text.replace("＋", "+")
    text = text.replace("—", "-")
    text = text.replace("－", "-")
    text = text.replace("～", "~")
    text = text.replace("：", ":")
    text = text.replace("，", ",")
    text = text.replace("；", ";")
    text = text.replace("？", "?")
    text = text.replace("！", "!")
    text = text.replace("…", "-")
    text = text.replace("‖", "||")
    text = text.replace("‘", "'")
    text = text.replace("’", "'")
    text = text.replace("｜", "|")
    text = text.replace("〃", "\"")
    text = text.replace("　", " ")
    text = text.replace("＼", "\\")
    return text
